config/routes.rb
Portfolio::Application.routes.draw do

  devise_for :users, controllers: {registrations: "users/registrations",
                                  passwords: "users/passwords",
                                  omniauth_callbacks: "omniauth_callbacks"}

  resources :posts do
    resources :comments
  end

  resources :projects do
    resources :comments
  end

 match 'users/sign_in', to: 'users#sign_in', via: :all

get '/contact', to: 'contact#index', via: :all

  root :to => 'projects#frontpage'

end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :name, :short_desc, :long_desc, :projectpic_url, :projecturl
  validates :projectpic_url, presence: true
  validates :name, length: { in: 4..255 }
  has_many :comments, as: :commentable
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def frontpage
    @projects = Project.all
  end

  def index
    @projects = Project.all
  end

  def new
    @projects = Project.all
    @project = Project.new
  end

  def create
    @projects = Project.all
    @project = Project.new(params[:project])
    if @project.save
      flash[:notice] = "Project was successfully added."
      redirect_to @project
    else
      flash[:alert] = "Project could not be saved."
      render action: "new"
    end
  end

  def show
    @projects = Project.all
    @project = Project.find(params[:id])
    @commentable = @project
    @comments = @commentable.comments
    @comment = Comment.new
  end

  def update
    @projects = Project.all
    @project = Project.find(params[:id])

    if @project.update_attributes(params[:project])
      redirect_to @project, notice: 'Project was successfully updated.'
    else
      flash[:alert] = "Project could not be saved."
      render :edit
    end
  end

  def edit
    @projects = Project.all
    @project = Project.find(params[:id])
  end

  def destroy
    @projects = Project.all
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end

end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :projecturl, "Project URL http://..." %><br />
    <%= f.text_field :projecturl %>
  </div>
  <div class="field">
    <%= f.label :short_desc %><br />
    <%= f.text_area :short_desc, size: "40x3" %>
  </div>
  <div class="field">
    <%= f.label :long_desc %><br />
    <%= f.text_area :long_desc %>
  </div>
  <div class="field">
    <%= f.label :projectpic_url, "Project picture URL http://..." %><br />
    <%= f.text_area :projectpic_url, size: "40x2" %>
  </div>
  <div class="actions">
    <%= f.submit "Edit Project" %>
  </div>
<% end %>

app/views/projects/_index.html.erb
<% @projects.reverse_each do |project| %>
  <div class="project" id ="<%= dom_id(project)%>">
    <div class="col-lg-6 col-md-12 col-sm-12 col-xs-6">
      <div class="panel panel-default item">
        <div class="panel-heading">
          <%= link_to(image_tag(project.projectpic_url, :class => "img-responsive item-img"), project_path(project)) %>
        </div>
        <div class="panel-body">
          <h4 class="item-title"><%= link_to project.name, project_path(project) %></h4>
          <p class="item-description"><%= project.short_desc %></p>
          <div class="nav">
            <% if current_user.present? %>
              <%= link_to 'Edit Project', edit_project_path(project) %>
              <%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?'} %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

<% end %>

<br />
<% if current_user.present? %>
  <%= link_to 'New Project', new_project_path %>
  <%= button_to "Sign Out", destroy_user_session_path, method: :delete %>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', root_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :projecturl, "Project URL http://..." %><br />
    <%= f.text_field :projecturl %>
  </div>
  <div class="field">
    <%= f.label :short_desc %><br />
    <%= f.text_area :short_desc, size: "40x3" %>
  </div>
  <div class="field">
    <%= f.label :long_desc %><br />
    <%= f.text_area :long_desc %>
  </div>
  <div class="field">
    <%= f.label :projectpic_url, "Project picture URL http://..." %><br />
    <%= f.text_area :projectpic_url, size: "40x2" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', root_path %>

app/views/projects/show.html.erb
<% content_for :hidefrontpage do %>
  #front_welcome {display: none}
<% end %>

<p id="notice"><%= notice %></p>
<div class="col-lg-12">
  <h1><p><center>
    <%= image_tag(@project.projectpic_url, :class => "img-responsive item-img") %></center>
    <%= @project.name %>
  </p></h1>

  <h1 class="spacer">___</h1>

  <p class="work">
    <%= @project.long_desc %>
  </p>
  <p class="work"><%= link_to @project.projecturl, @project.projecturl, :target => "_blank" %></p>
  <% if current_user.present? %>
    <%= link_to 'Edit Project', edit_project_path(@project) %> |
    <%= link_to 'Back', root_path %>
  <% end %>