config/routes.rb
Portfolio::Application.routes.draw do

  devise_for :users, controllers: {registrations: "users/registrations",
                                  passwords: "users/passwords",
                                  omniauth_callbacks: "omniauth_callbacks"}

  resources :posts do
    resources :comments
  end

  resources :projects do
    resources :comments
  end

 match 'users/sign_in', to: 'users#sign_in', via: :all

get '/contact', to: 'contact#index', via: :all

  root :to => 'projects#frontpage'

end

app/views/layouts/_layouttitle.html.erb
    <body class="page-index">
        <div class="container" id="container">

            <div class="row top">
                <div class="col-lg-8 col-md-8 col-sm-7 col-left">
                    <div class="name"><%= link_to "Matt Sayre", root_path %></div>
                </div>
              <div class="col-lg-4 col-md-4 col-sm-5 col-right">
                    <nav>
                        <ul class="list-inline" id="menu">

app/views/layouts/_layouttop.html.erb
<html>
    <head>
    <meta charset="utf-8">
    <title>Matt Sayre's Blog and Portfolio</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <link rel="icon" type="image/png" href="/assets/favicon.png">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-45679901-1', 'gitmatt.com');
  ga('send', 'pageview');

</script>
    </head>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<%= render 'layouts/layouttop' %>

    <%= render 'layouts/layouttitle' %>
                            <li class="active">
                                <%= link_to "work", root_path %>
                            </li><!--
                            --><li>
                                <%= link_to "blog", posts_path %>
                            </li><!--
                            --><li>
                                <%= link_to "contact", contact_path %>
                            </li><!--
                            --><li>
                                <%= link_to(image_tag("/assets/icon-linkedin.png", :class => "social"), "http://www.linkedin.com/in/mlsayre", :target => "_blank") %>
                                <%= link_to(image_tag("/assets/github-128.png", :class => "social"), "http://github.com/mlsayre", :target => "_blank") %>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
            <div class="row bottom">
                <div class="col-lg-8 col-md-8 col-sm-7 col-left">
                    <div>
                        <section>
                            <div class="row text-center">
                              <%= yield %>
                                <div class="col-lg-12" id="front_welcome">
                                <style><%= yield :hidefrontpage %></style>
                                    <!--activity image-->
                                    <center><img class="img-responsive" src="assets/seattle.jpg" alt="Welcome"></center>

                                    <!--activity title -->
                                    <h1>Welcome to GitMatt - my online portfolio and blog</h1>
                                    <h1 class="spacer">___</h1>

                                    <!--activity descritpion-->
                                    <p class="work">Seattle, WA Web Developer</p>
                                    <p>I am a professional web designer and developer versed in Ruby on Rails, HTML, CSS, Javascript, jQuery, and various other technologies. I look forward to every web production or design challenge no matter how big or small. The process of finding solutions is both exhilarating and addictive and I wouldn't trade my job for any other. Need to get your latest idea online? Let's talk!</p>

                                </div>
                            </div>
                        </section>
                    </div>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-5 col-right">
                    <div id="scroll-shadow"></div>

                    <h1 class="visible-xs section-header">Latest work</h1>
                    <h1 class="visible-xs text-center spacer">___</h1>

                    <!--work choice-->
                    <div class="item-choice">
                        <div class="filter">Matt's Portfolio</div>
                        <hr>
                    </div>

                    <section class="row" id="Grid">
                       <%= render 'projects/index' %>
                    </section>
                    <a class="btn btn-block scroll-top visible-xs">
                        <img src="/assets/icon-chevron.png" alt="Scroll top">
                    </a>
                </div>
            </div>
        </div>

    </body>
</html>

app/views/layouts/applicationold.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Portfolio of Matt Sayre</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<!-- Side Menu -->
    <a id="menu-toggle" href="#" class="btn btn-primary btn-lg toggle"><i class="icon-reorder"></i></a>
    <div id="sidebar-wrapper">
      <ul class="sidebar-nav">
        <li class="sidebar-brand"><a href="http://thegamecomposer.com">Matt's Portfolio</a></li>
        <li><a href="#top">Home</a></li>
        <li><a href="#portfolio">Portfolio</a></li>
        <li><a href="#services">Services</a></li>
        <li><a href="#">About</a></li>
        <li><a href="#">Contact</a></li>
        <a id="menu-close" href="#" class="btn btn-default btn-lg pull-right toggle"><i class="icon-remove"></i></a>
      </ul>
    </div>
    <!-- /Side Menu -->

    <!-- Full Page Image Header Area -->
    <div id="top" class="header">
      <div class="vert-text">
        <h1>Matt Sayre's Portfolio</h1>
        <h3>Ruby on Rails, <em>Ruby</em> on <em>Rails.</em></h3>
        <a href="#intro" class="btn btn-default btn-lg">Matt's Blog</a>
          <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <div id="user_header">
    <% if current_user %>
      Logged in as <%= current_user.email %>. <br />
      <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Sign Up", new_user_registration_path %> or
      <%= link_to "Sign In", new_user_session_path %>
      <%= link_to "Sign in with Twitter", user_omniauth_authorize_path(:twitter) %>
    <% end %>
  </div>
      </div>
    </div>
    <!-- /Full Page Image Header Area -->
   <!-- Intro -->
    <div id="intro" class="intro">
      <div class="container">
        <div class="row">
          <div class="col-md-6 col-md-offset-3 text-center">
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
    <!-- /Intro -->

  <!-- Services -->
    <div id="services" class="services">
      <div class="container">
        <div class="row">
          <div class="col-md-4 col-md-offset-4 text-center">
            <h2>Our Services</h2>
            <hr>
          </div>
        </div>
        <div class="row">
          <div class="col-md-2 col-md-offset-2 text-center">
            <div class="service-item">
              <i class="service-icon icon-rocket"></i>
              <h4>Spacecraft Repair</h4>
              <p>Did your navigation system shut down in the middle of that asteroid field? We can repair any dings and scrapes to your spacecraft!</p>
            </div>
          </div>
          <div class="col-md-2 text-center">
            <div class="service-item">
              <i class="service-icon icon-magnet"></i>
              <h4>Problem Solving</h4>
              <p>Need to know how magnets work? Our problem solving solutions team can help you identify problems and conduct exploratory research.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- /Services -->

      <!-- Callout -->
    <div class="callout">
      <div class="vert-text">
        <h1>A Dramatic Text Area</h1>
      </div>
    </div>
    <!-- /Callout -->

    <!-- Portfolio -->
    <div id ="portfolio" class="portfolio">
      <div class="container">
        <div class="row">
          <div class="col-md-4 col-md-offset-4 text-center">
            <h2>Our Work</h2>
            <hr>
          </div>
        </div>
        <div class="row">
          <div class="col-md-4 col-md-offset-2 text-center">
            <div class="portfolio-item">
              <a href="#top">
                <%= image_tag("portfolio-1.jpg", :class => "img-portfolio img-responsive") %> </a>
              <h4>Cityscape</h4>
            </div>
          </div>
          <div class="col-md-4 text-center">
            <div class="portfolio-item">
              <a href="#top">
                <%= image_tag("portfolio-2.jpg", :class => "img-portfolio img-responsive") %> </a>
              <h4>Is That On Fire?</h4>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-4 col-md-offset-2 text-center">
            <div class="portfolio-item">
              <a href="#top">
                <%= image_tag("portfolio-3.jpg", :class => "img-portfolio img-responsive") %></a>
              <h4>Stop Sign</h4>
            </div>
          </div>
          <div class="col-md-4 text-center">
            <div class="portfolio-item">
              <a href="#top">
                <%= image_tag("portfolio-4.jpg", :class => "img-portfolio img-responsive") %></a>
              <h4>Narrow Focus</h4>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- /Portfolio -->
<!-- Call to Action -->
    <div class="call-to-action">
      <div class="container">
        <div class="row">
          <div class="col-md-6 col-md-offset-3 text-center">
            <h3>The buttons below are impossible to resist.</h3>
            <a href="#top" class="btn btn-lg btn-default">Click Me!</a>
            <a href="#top" class="btn btn-lg btn-primary">Look at Me!</a>
          </div>
        </div>
      </div>
    </div>
    <!-- /Call to Action -->
<% flash.each do |key, value| %>
    <div class="<%= flash_class(key) %>">
      <%= value %>
    </div>
  <% end %>
    <!-- Footer -->
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-md-6 col-md-offset-3 text-center">
            <ul class="list-inline">
              <li><i class="icon-facebook icon-2x"></i></li>
              <li><i class="icon-twitter icon-2x"></i></li>
              <li><i class="icon-dribbble icon-2x"></i></li>
            </ul>
            <hr>
            <p>Copyright &copy; Matt Sayre 2013</p>
          </div>
        </div>
      </div>
    </footer>
    <!-- /Footer -->

</body>
</html>

app/views/layouts/blog.html.erb
<!DOCTYPE html>

<%= render '/layouts/layouttop' %>

    <%= render 'layouts/layouttitle' %>

                            <li>
                                <%= link_to "work", root_path %>
                            </li><!--
                            --><li class=" active">
                                <%= link_to "blog", posts_path %>
                            </li><!--
                            --><li>
                                <%= link_to "contact", contact_path %>
                            </li><!--
                            --><li>
                                <%= link_to(image_tag("/assets/icon-linkedin.png", :class => "social"), "http://www.linkedin.com/in/mlsayre", :target => "_blank") %>
                                <%= link_to(image_tag("/assets/github-128.png", :class => "social"), "http://github.com/mlsayre", :target => "_blank") %>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
            <div class="row bottom">
                <div class="col-lg-8 col-md-8 col-sm-7 col-left">
                    <div>
                        <section>
                          <%= yield %>
                          <div id="front_blog">
                            <style><%= yield :hidefrontblog %></style>
                            <!--article title-->
                            <h1><%= @lastpost.title %></h1>
                            <h1 class="spacer">______</h1>
                            <h4>by <%= @lastpost.creator %></h4>

                            <!--article date-->
                            <p class="article-date"><%= @lastpost.created_at.strftime("%b %d, %Y") %> | <%= @lastpost.created_at.strftime("%l:%M%P") %></p>

                            <!--article tags-->
                            <p class="article-tags">
                                Categories: <%= @lastpost.category %>
                            </p>

                            <!--article content-->
                            <p class="article-description"><strong><%= @lastpost.summary %></strong>
                            <br><br>
                            <%= dat_markdown(@lastpost.content) %>
                            </p>

                            <!--navigation-->
                            <ul class="pager">
                                <li class="previous"><%= link_to 'Prev', post_path(@post.previous_post)  if @post.previous_post %></li>
                                <li class="next"><%= link_to 'Next', post_path(@post.next_post)  if @post.next_post %></li>
                            </ul>
                            <hr>
                          </div>
                        </section>
                    </div>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-5 col-right">
                    <div id="scroll-shadow"></div>
                    <h1 class="visible-xs section-header" id="posts-list">Last posts</h1>
                    <h1 class="visible-xs text-center spacer">___</h1>

                    <section class="blog">

                      <%= render 'index' %>

                    </section>
                    <!--<a class="btn btn-default btn-lg btn-block load-more">Load more</a> -->
                    <a class="btn btn-block scroll-top visible-xs">
                        <img src="/assets/icon-chevron.png" alt="Scroll top">
                    </a>
                </div>
            </div>
        </div>
    </body>
</html>

app/views/layouts/contact.html.erb
<!DOCTYPE html>

<%= render '/layouts/layouttop' %>

    <%= render 'layouts/layouttitle' %>
                            <li>
                                <%= link_to "work", root_path %>
                            </li><!--
                            --><li>
                                 <%= link_to "blog", posts_path %>
                            </li><!--
                            --><li class="active">
                                 <%= link_to "contact", contact_url %>
                            </li><!--
                            --><li>
                                <%= link_to(image_tag("/assets/icon-linkedin.png", :class => "social"), "http://www.linkedin.com/in/mlsayre", :target => "_blank") %>
                                <%= link_to(image_tag("/assets/github-128.png", :class => "social"), "http://github.com/mlsayre", :target => "_blank") %>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
            <div class="row bottom">
                <div class="col-lg-8 col-md-8 col-sm-7 col-left">
                    <section>
                        <div class="row">
                            <div class="col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2">

                                <!--input contact-->
                                <h1>Contact</h1>
                                <h1 class="spacer">___</h1>
                                <p>If you have any web development questions or if you are a company in need of a friendly, efficient, and enthusiastic web developer, please feel free to send me an email. I promise to reply as soon as someone breaks me out of the carbonite and my wookie reads me your message.</p>
                                <br />
                                <p><%= mail_to 'mlsayre@gmail.com', 'Click to email me...' %>
                                <hr>

                            </div>
                        </div>
                    </section>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-5 col-right">
                <div id="scroll-shadow"></div>
                    <section>
                        <div class="row">
                            <div class="col-lg-12">

                                <!--panel contact-->
                                <div class="panel panel-default item">
                                    <div class="panel-heading">
                                        <a href="#">

                                            <!--your image-->
                                            <img class="img-responsive item-img" src="https://s3-us-west-2.amazonaws.com/portmls/portfolio/mefrozen.jpg" alt="Me. Frozen.">

                                        </a>
                                    </div>
                                    <div class="panel-body">

                                        <!--your name-->
                                        <a href="#"><h4 class="item-title">Matt Sayre</h4></a>

                                        <!--your profession / where you live-->
                                        <p class="item-category">Web Developer, Seattle</p>

                                        <!--your descritpion -->
                                        <p class="item-description">I am a professional web developer versed in Ruby on Rails, HTML, CSS, Javascript, jQuery, and various other technologies. I look forward to every web production or design challenge no matter how big or small. The process of finding solutions is both exhilarating and addictive and I wouldn't trade my job for any other. Let's talk!</p>
                                        <hr>

                                        <!--social networks-->
                                        <div class="item-social text-center">
                                            <%= link_to(image_tag("/assets/icon-linkedin.png", :class => "social"), "http://www.linkedin.com/in/mlsayre", :target => "_blank") %>
                                            <%= link_to(image_tag("/assets/github-128.png", :class => "social"), "http://github.com/mlsayre", :target => "_blank") %>

                                        </div>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </section>
                </div>
            </div>
        </div>

        <script src="js/jquery.js"></script>
        <!-- FASTCLICK -->
        <script src="js/plugins/fastclick/fastclick.js"></script>
        <!-- SMOOTH SCROLL -->
        <script src="js/plugins/smooth-scroll/jquery.smooth-scroll.min.js"></script>
        <!-- MIXITUP -->
        <script src="js/plugins/mixitup/jquery.mixitup.min.js"></script>

        <script src="js/main.js"></script>
    </body>
</html>

app/views/layouts/devise.html.erb
<h2>Sign in</h2>

<%= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
  <div><%= f.label :email %><br />
  <%= f.email_field :email, :autofocus => true %></div>

  <div><%= f.label :password %><br />
  <%= f.password_field :password %></div>

  <% if devise_mapping.rememberable? -%>
    <div><%= f.check_box :remember_me %> <%= f.label :remember_me %></div>
  <% end -%>

  <div><%= f.submit "Sign in" %></div>
<% end %>

<%= render "devise/shared/links" %>

      <%= render "devise/shared/links" %>